// Generated by tools/build-assets.py from the original sheets. Do not edit by hand.
window.PopoGame = window.PopoGame || {};
PopoGame.SHEET_DATA = {
 "fishing": {
  "width": 1860,
  "height": 1305,
  "frames": [
   {
    "row": 0,
    "col": 0,
    "cellX": 0,
    "cellY": 0,
    "cellW": 620,
    "cellH": 435,
    "box": [
     107,
     105,
     535,
     402
    ],
    "seat": [
     220,
     385
    ],
    "rodTip": [
     532,
     130
    ],
    "bodyArea": 25571
   },
   {
    "row": 0,
    "col": 1,
    "cellX": 620,
    "cellY": 0,
    "cellW": 620,
    "cellH": 435,
    "box": [
     729,
     63,
     1143,
     402
    ],
    "seat": [
     840,
     383
    ],
    "rodTip": [
     1139,
     70
    ],
    "bodyArea": 24387
   },
   {
    "row": 0,
    "col": 2,
    "cellX": 1240,
    "cellY": 0,
    "cellW": 620,
    "cellH": 435,
    "box": [
     1345,
     50,
     1730,
     400
    ],
    "seat": [
     1450,
     383
    ],
    "rodTip": [
     1726,
     56
    ],
    "bodyArea": 24584
   },
   {
    "row": 1,
    "col": 0,
    "cellX": 0,
    "cellY": 435,
    "cellW": 620,
    "cellH": 435,
    "box": [
     36,
     487,
     356,
     837
    ],
    "seat": [
     213,
     822
    ],
    "rodTip": [
     43,
     491
    ],
    "bodyArea": 22268
   },
   {
    "row": 1,
    "col": 1,
    "cellX": 620,
    "cellY": 435,
    "cellW": 620,
    "cellH": 435,
    "box": [
     730,
     529,
     1174,
     837
    ],
    "seat": [
     839,
     818
    ],
    "rodTip": [
     1170,
     537
    ],
    "bodyArea": 22577
   },
   {
    "row": 1,
    "col": 2,
    "cellX": 1240,
    "cellY": 435,
    "cellW": 620,
    "cellH": 435,
    "box": [
     1351,
     561,
     1758,
     836
    ],
    "seat": [
     1463,
     817
    ],
    "rodTip": [
     1753,
     568
    ],
    "bodyArea": 22976
   },
   {
    "row": 2,
    "col": 0,
    "cellX": 0,
    "cellY": 870,
    "cellW": 620,
    "cellH": 435,
    "box": [
     109,
     991,
     596,
     1271
    ],
    "seat": [
     219,
     1255
    ],
    "rodTip": [
     593,
     1003
    ],
    "bodyArea": 24226
   },
   {
    "row": 2,
    "col": 1,
    "cellX": 620,
    "cellY": 870,
    "cellW": 620,
    "cellH": 435,
    "box": [
     730,
     994,
     1129,
     1272
    ],
    "seat": [
     842,
     1254
    ],
    "rodTip": [
     1125,
     1012
    ],
    "bodyArea": 23256
   },
   {
    "row": 2,
    "col": 2,
    "cellX": 1240,
    "cellY": 870,
    "cellW": 620,
    "cellH": 435,
    "box": [
     1351,
     938,
     1745,
     1271
    ],
    "seat": [
     1461,
     1253
    ],
    "rodTip": [
     1741,
     946
    ],
    "bodyArea": 22826
   }
  ]
 },
 "rowing": {
  "width": 1254,
  "height": 1254,
  "frames": [
   {
    "row": 0,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 0,
    "raftLeft": 23,
    "raftRight": 381,
    "raftBottom": 371,
    "bodyArea": 9985,
    "box": [
     22,
     118,
     383,
     378
    ]
   },
   {
    "row": 0,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 0,
    "raftLeft": 440,
    "raftRight": 822,
    "raftBottom": 370,
    "bodyArea": 9479,
    "box": [
     440,
     138,
     824,
     392
    ]
   },
   {
    "row": 0,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 0,
    "raftLeft": 861,
    "raftRight": 1227,
    "raftBottom": 371,
    "bodyArea": 9890,
    "box": [
     860,
     161,
     1228,
     410
    ]
   },
   {
    "row": 1,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 418,
    "raftLeft": 25,
    "raftRight": 388,
    "raftBottom": 785,
    "bodyArea": 10273,
    "box": [
     24,
     545,
     390,
     796
    ]
   },
   {
    "row": 1,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 418,
    "raftLeft": 442,
    "raftRight": 806,
    "raftBottom": 785,
    "bodyArea": 9880,
    "box": [
     441,
     534,
     806,
     791
    ]
   },
   {
    "row": 1,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 418,
    "raftLeft": 863,
    "raftRight": 1227,
    "raftBottom": 785,
    "bodyArea": 10951,
    "box": [
     865,
     531,
     1229,
     791
    ]
   },
   {
    "row": 2,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 836,
    "raftLeft": 25,
    "raftRight": 387,
    "raftBottom": 1176,
    "bodyArea": 10045,
    "box": [
     24,
     917,
     388,
     1183
    ]
   },
   {
    "row": 2,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 836,
    "raftLeft": 445,
    "raftRight": 808,
    "raftBottom": 1177,
    "bodyArea": 10459,
    "box": [
     444,
     926,
     810,
     1184
    ]
   },
   {
    "row": 2,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 836,
    "raftLeft": 860,
    "raftRight": 1226,
    "raftBottom": 1177,
    "bodyArea": 10311,
    "box": [
     860,
     917,
     1227,
     1184
    ]
   }
  ]
 }
};
PopoGame.FISH_ATLAS = {"width": 2048, "height": 550, "boxes": {"triangle": [0, 0, 252, 241], "square": [260, 0, 495, 258], "rectangle": [503, 0, 788, 228], "circle": [796, 0, 1056, 256], "rhombus": [1064, 0, 1298, 284], "parallelogram": [1306, 0, 1583, 228], "trapezium": [1591, 0, 1865, 234], "pentagon": [0, 292, 248, 550], "hexagon": [256, 292, 514, 546], "octagon": [522, 292, 761, 542], "nonagon": [769, 292, 1011, 539], "decagon": [1019, 292, 1264, 542], "oval": [1272, 292, 1566, 490], "semicircle": [1574, 292, 1749, 541], "triangle-right": [1757, 292, 2005, 515]}};
