// Generated by tools/build-assets.py from the original sheets. Do not edit by hand.
window.PopoGame = window.PopoGame || {};
PopoGame.SHEET_DATA = {
 "fishing": {
  "width": 1254,
  "height": 1254,
  "frames": [
   {
    "row": 0,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 0,
    "raftLeft": 24,
    "raftRight": 367,
    "raftBottom": 383,
    "bodyArea": 8199,
    "rodTip": [
     353,
     103
    ],
    "rodAxis": [
     306.4288990825688,
     137.23394495412845,
     0.6862429150120134,
     -0.7273724366483889
    ],
    "box": [
     24,
     96,
     368,
     389
    ]
   },
   {
    "row": 0,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 0,
    "raftLeft": 423,
    "raftRight": 785,
    "raftBottom": 383,
    "bodyArea": 9284,
    "rodTip": [
     775,
     130
    ],
    "rodAxis": [
     705.7056962025316,
     177.376582278481,
     0.7126626936177762,
     -0.7015068674827464
    ],
    "box": [
     428,
     122,
     785,
     390
    ]
   },
   {
    "row": 0,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 0,
    "raftLeft": 841,
    "raftRight": 1205,
    "raftBottom": 383,
    "bodyArea": 9158,
    "rodTip": [
     1192,
     123
    ],
    "rodAxis": [
     1121.2304316020484,
     175.87856620336504,
     0.6907383104486313,
     -0.7231048239906647
    ],
    "box": [
     842,
     115,
     1205,
     390
    ]
   },
   {
    "row": 1,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 418,
    "raftLeft": 24,
    "raftRight": 368,
    "raftBottom": 782,
    "bodyArea": 9027,
    "rodTip": [
     355,
     515
    ],
    "rodAxis": [
     292.0299539170507,
     564.2549923195085,
     0.6733357711388711,
     -0.7393368239881075
    ],
    "box": [
     24,
     508,
     370,
     789
    ]
   },
   {
    "row": 1,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 418,
    "raftLeft": 423,
    "raftRight": 784,
    "raftBottom": 783,
    "bodyArea": 9790,
    "rodTip": [
     782,
     527
    ],
    "rodAxis": [
     711.4306513409962,
     579.0597701149426,
     0.6992666999051773,
     -0.7148608832519253
    ],
    "box": [
     428,
     519,
     786,
     789
    ]
   },
   {
    "row": 1,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 418,
    "raftLeft": 842,
    "raftRight": 1204,
    "raftBottom": 782,
    "bodyArea": 9189,
    "rodTip": [
     1192,
     513
    ],
    "rodAxis": [
     1145.2212290502794,
     542.5519553072626,
     0.7447826362852012,
     -0.6673071441907884
    ],
    "box": [
     846,
     506,
     1206,
     789
    ]
   },
   {
    "row": 2,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 836,
    "raftLeft": 25,
    "raftRight": 368,
    "raftBottom": 1178,
    "bodyArea": 9267,
    "rodTip": [
     384,
     936
    ],
    "rodAxis": [
     310.82223962411905,
     980.0062646828504,
     0.7636993100295175,
     -0.6455721213469793
    ],
    "box": [
     24,
     927,
     386,
     1186
    ]
   },
   {
    "row": 2,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 836,
    "raftLeft": 424,
    "raftRight": 784,
    "raftBottom": 1180,
    "bodyArea": 9548,
    "rodTip": [
     784,
     934
    ],
    "rodAxis": [
     720.7106194690266,
     975.4061946902655,
     0.73748395244234,
     -0.6753646569743077
    ],
    "box": [
     426,
     926,
     786,
     1188
    ]
   },
   {
    "row": 2,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 836,
    "raftLeft": 842,
    "raftRight": 1205,
    "raftBottom": 1181,
    "bodyArea": 9559,
    "rodTip": [
     1194,
     916
    ],
    "rodAxis": [
     1146.3393461104847,
     945.3077790304396,
     0.7404731455032957,
     -0.6720859474713446
    ],
    "box": [
     842,
     908,
     1206,
     1189
    ]
   }
  ]
 },
 "casting": {
  "width": 1254,
  "height": 1254,
  "frames": [
   {
    "row": 0,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 0,
    "raftLeft": 26,
    "raftRight": 355,
    "raftBottom": 395,
    "bodyArea": 8062,
    "rodTip": [
     358,
     201
    ],
    "rodAxis": [
     311.4425981873112,
     229.61631419939576,
     0.8344927484794524,
     -0.5510189223023193
    ],
    "box": [
     26,
     188,
     362,
     403
    ]
   },
   {
    "row": 0,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 0,
    "raftLeft": 440,
    "raftRight": 788,
    "raftBottom": 395,
    "bodyArea": 8097,
    "rodTip": [
     748,
     124
    ],
    "rodAxis": [
     689.5073068893528,
     179.7787056367432,
     0.6254412582620416,
     -0.7802712556948348
    ],
    "box": [
     439,
     121,
     790,
     403
    ]
   },
   {
    "row": 0,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 0,
    "raftLeft": 857,
    "raftRight": 1207,
    "raftBottom": 396,
    "bodyArea": 8387,
    "rodTip": [
     1003,
     129
    ],
    "rodAxis": [
     1032.580310880829,
     172.9417098445596,
     0.5908406429541405,
     0.8067882836491479
    ],
    "box": [
     856,
     114,
     1208,
     404
    ]
   },
   {
    "row": 1,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 418,
    "raftLeft": 26,
    "raftRight": 385,
    "raftBottom": 799,
    "bodyArea": 9527,
    "rodTip": [
     131,
     475
    ],
    "rodAxis": [
     148.86695278969958,
     500.0257510729614,
     0.49721291803562806,
     0.8676285577011028
    ],
    "box": [
     25,
     472,
     387,
     806
    ]
   },
   {
    "row": 1,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 418,
    "raftLeft": 439,
    "raftRight": 782,
    "raftBottom": 799,
    "bodyArea": 8367,
    "rodTip": [
     825,
     537
    ],
    "rodAxis": [
     770.5786082474227,
     564.2628865979382,
     0.8496813762420344,
     -0.527296462028186
    ],
    "box": [
     438,
     532,
     827,
     806
    ]
   },
   {
    "row": 1,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 418,
    "raftLeft": 838,
    "raftRight": 1178,
    "raftBottom": 799,
    "bodyArea": 8097,
    "rodTip": [
     1092,
     607
    ],
    "rodAxis": [
     1046.7799717912553,
     635.6770098730607,
     0.8224279015264513,
     -0.5688693582807899
    ],
    "box": [
     846,
     591,
     1179,
     806
    ]
   },
   {
    "row": 2,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 836,
    "raftLeft": 29,
    "raftRight": 369,
    "raftBottom": 1166,
    "bodyArea": 8134,
    "rodTip": [
     336,
     993
    ],
    "rodAxis": [
     296.32699619771864,
     1011.0152091254753,
     0.8948269799448327,
     -0.44641312252532406
    ],
    "box": [
     28,
     963,
     370,
     1174
    ]
   },
   {
    "row": 2,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 836,
    "raftLeft": 438,
    "raftRight": 775,
    "raftBottom": 1166,
    "bodyArea": 8132,
    "rodTip": [
     779,
     986
    ],
    "rodAxis": [
     735.9263157894737,
     1007.5278195488722,
     0.8729214928025895,
     -0.4878607049182161
    ],
    "box": [
     438,
     955,
     781,
     1173
    ]
   },
   {
    "row": 2,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 836,
    "raftLeft": 855,
    "raftRight": 1183,
    "raftBottom": 1165,
    "bodyArea": 8120,
    "rodTip": [
     1195,
     983
    ],
    "rodAxis": [
     1152.278523489933,
     1005.1677852348994,
     0.848546668292959,
     -0.5291205455554708
    ],
    "box": [
     855,
     959,
     1197,
     1173
    ]
   }
  ]
 },
 "rowing": {
  "width": 1254,
  "height": 1254,
  "frames": [
   {
    "row": 0,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 0,
    "raftLeft": 23,
    "raftRight": 381,
    "raftBottom": 371,
    "bodyArea": 9985,
    "box": [
     22,
     118,
     383,
     378
    ]
   },
   {
    "row": 0,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 0,
    "raftLeft": 440,
    "raftRight": 822,
    "raftBottom": 370,
    "bodyArea": 9479,
    "box": [
     440,
     138,
     824,
     392
    ]
   },
   {
    "row": 0,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 0,
    "raftLeft": 861,
    "raftRight": 1227,
    "raftBottom": 371,
    "bodyArea": 9890,
    "box": [
     860,
     161,
     1228,
     410
    ]
   },
   {
    "row": 1,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 418,
    "raftLeft": 25,
    "raftRight": 388,
    "raftBottom": 785,
    "bodyArea": 10273,
    "box": [
     24,
     545,
     390,
     796
    ]
   },
   {
    "row": 1,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 418,
    "raftLeft": 442,
    "raftRight": 806,
    "raftBottom": 785,
    "bodyArea": 9880,
    "box": [
     441,
     534,
     806,
     791
    ]
   },
   {
    "row": 1,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 418,
    "raftLeft": 863,
    "raftRight": 1227,
    "raftBottom": 785,
    "bodyArea": 10951,
    "box": [
     865,
     531,
     1229,
     791
    ]
   },
   {
    "row": 2,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 836,
    "raftLeft": 25,
    "raftRight": 387,
    "raftBottom": 1176,
    "bodyArea": 10045,
    "box": [
     24,
     917,
     388,
     1183
    ]
   },
   {
    "row": 2,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 836,
    "raftLeft": 445,
    "raftRight": 808,
    "raftBottom": 1177,
    "bodyArea": 10459,
    "box": [
     444,
     926,
     810,
     1184
    ]
   },
   {
    "row": 2,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 836,
    "raftLeft": 860,
    "raftRight": 1226,
    "raftBottom": 1177,
    "bodyArea": 10311,
    "box": [
     860,
     917,
     1227,
     1184
    ]
   }
  ]
 }
};
PopoGame.FISH_ATLAS = {"width": 2048, "height": 550, "boxes": {"triangle": [0, 0, 252, 241], "square": [260, 0, 495, 258], "rectangle": [503, 0, 788, 228], "circle": [796, 0, 1056, 256], "rhombus": [1064, 0, 1298, 284], "parallelogram": [1306, 0, 1583, 228], "trapezium": [1591, 0, 1865, 234], "pentagon": [0, 292, 248, 550], "hexagon": [256, 292, 514, 546], "octagon": [522, 292, 761, 542], "nonagon": [769, 292, 1011, 539], "decagon": [1019, 292, 1264, 542], "oval": [1272, 292, 1566, 490], "semicircle": [1574, 292, 1749, 541], "triangle-right": [1757, 292, 2005, 515]}};
