// Generated by tools/build-assets.py from the original sheets. Do not edit by hand.
window.PopoGame = window.PopoGame || {};
PopoGame.SHEET_DATA = {
 "fishing": {
  "width": 1254,
  "height": 1254,
  "frames": [
   {
    "row": 0,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 0,
    "raftLeft": 24,
    "raftRight": 367,
    "raftBottom": 383,
    "bodyArea": 8199,
    "rodTip": [
     353,
     103
    ],
    "box": [
     50,
     96,
     368,
     389
    ]
   },
   {
    "row": 0,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 0,
    "raftLeft": 423,
    "raftRight": 785,
    "raftBottom": 383,
    "bodyArea": 9284,
    "rodTip": [
     775,
     130
    ],
    "box": [
     449,
     122,
     785,
     390
    ]
   },
   {
    "row": 0,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 0,
    "raftLeft": 841,
    "raftRight": 1205,
    "raftBottom": 383,
    "bodyArea": 9158,
    "rodTip": [
     1192,
     123
    ],
    "box": [
     866,
     115,
     1205,
     390
    ]
   },
   {
    "row": 1,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 418,
    "raftLeft": 24,
    "raftRight": 368,
    "raftBottom": 782,
    "bodyArea": 9027,
    "rodTip": [
     355,
     515
    ],
    "box": [
     48,
     508,
     370,
     789
    ]
   },
   {
    "row": 1,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 418,
    "raftLeft": 423,
    "raftRight": 784,
    "raftBottom": 783,
    "bodyArea": 9790,
    "rodTip": [
     782,
     527
    ],
    "box": [
     448,
     519,
     786,
     789
    ]
   },
   {
    "row": 1,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 418,
    "raftLeft": 842,
    "raftRight": 1204,
    "raftBottom": 782,
    "bodyArea": 9189,
    "rodTip": [
     1192,
     513
    ],
    "box": [
     867,
     506,
     1206,
     789
    ]
   },
   {
    "row": 2,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 836,
    "raftLeft": 25,
    "raftRight": 368,
    "raftBottom": 1178,
    "bodyArea": 9267,
    "rodTip": [
     384,
     936
    ],
    "box": [
     48,
     927,
     386,
     1186
    ]
   },
   {
    "row": 2,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 836,
    "raftLeft": 424,
    "raftRight": 784,
    "raftBottom": 1180,
    "bodyArea": 9548,
    "rodTip": [
     784,
     934
    ],
    "box": [
     448,
     926,
     786,
     1188
    ]
   },
   {
    "row": 2,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 836,
    "raftLeft": 842,
    "raftRight": 1205,
    "raftBottom": 1181,
    "bodyArea": 9559,
    "rodTip": [
     1194,
     916
    ],
    "box": [
     867,
     908,
     1206,
     1189
    ]
   }
  ]
 },
 "casting": {
  "width": 1254,
  "height": 1254,
  "frames": [
   {
    "row": 0,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 0,
    "raftLeft": 26,
    "raftRight": 355,
    "raftBottom": 395,
    "bodyArea": 8062,
    "rodTip": [
     358,
     201
    ],
    "box": [
     46,
     188,
     362,
     403
    ]
   },
   {
    "row": 0,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 0,
    "raftLeft": 440,
    "raftRight": 788,
    "raftBottom": 395,
    "bodyArea": 8097,
    "rodTip": [
     748,
     124
    ],
    "box": [
     461,
     121,
     790,
     403
    ]
   },
   {
    "row": 0,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 0,
    "raftLeft": 857,
    "raftRight": 1207,
    "raftBottom": 396,
    "bodyArea": 8387,
    "rodTip": [
     1003,
     129
    ],
    "box": [
     878,
     114,
     1208,
     404
    ]
   },
   {
    "row": 1,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 418,
    "raftLeft": 26,
    "raftRight": 385,
    "raftBottom": 799,
    "bodyArea": 9527,
    "rodTip": [
     131,
     475
    ],
    "box": [
     48,
     472,
     387,
     806
    ]
   },
   {
    "row": 1,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 418,
    "raftLeft": 439,
    "raftRight": 782,
    "raftBottom": 799,
    "bodyArea": 8367,
    "rodTip": [
     825,
     537
    ],
    "box": [
     461,
     532,
     827,
     806
    ]
   },
   {
    "row": 1,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 418,
    "raftLeft": 838,
    "raftRight": 1178,
    "raftBottom": 799,
    "bodyArea": 8097,
    "rodTip": [
     1092,
     607
    ],
    "box": [
     846,
     591,
     1179,
     806
    ]
   },
   {
    "row": 2,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 836,
    "raftLeft": 29,
    "raftRight": 369,
    "raftBottom": 1166,
    "bodyArea": 8134,
    "rodTip": [
     336,
     993
    ],
    "box": [
     51,
     963,
     370,
     1174
    ]
   },
   {
    "row": 2,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 836,
    "raftLeft": 438,
    "raftRight": 775,
    "raftBottom": 1166,
    "bodyArea": 8132,
    "rodTip": [
     779,
     986
    ],
    "box": [
     462,
     955,
     781,
     1173
    ]
   },
   {
    "row": 2,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 836,
    "raftLeft": 855,
    "raftRight": 1183,
    "raftBottom": 1165,
    "bodyArea": 8120,
    "rodTip": [
     1195,
     983
    ],
    "box": [
     876,
     959,
     1197,
     1173
    ]
   }
  ]
 },
 "rowing": {
  "width": 1254,
  "height": 1254,
  "frames": [
   {
    "row": 0,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 0,
    "raftLeft": 23,
    "raftRight": 381,
    "raftBottom": 371,
    "bodyArea": 9985,
    "box": [
     47,
     118,
     383,
     378
    ]
   },
   {
    "row": 0,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 0,
    "raftLeft": 440,
    "raftRight": 822,
    "raftBottom": 370,
    "bodyArea": 9479,
    "box": [
     465,
     138,
     824,
     392
    ]
   },
   {
    "row": 0,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 0,
    "raftLeft": 861,
    "raftRight": 1227,
    "raftBottom": 371,
    "bodyArea": 9890,
    "box": [
     884,
     161,
     1228,
     410
    ]
   },
   {
    "row": 1,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 418,
    "raftLeft": 25,
    "raftRight": 388,
    "raftBottom": 785,
    "bodyArea": 10273,
    "box": [
     49,
     545,
     390,
     796
    ]
   },
   {
    "row": 1,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 418,
    "raftLeft": 442,
    "raftRight": 806,
    "raftBottom": 785,
    "bodyArea": 9880,
    "box": [
     466,
     534,
     806,
     791
    ]
   },
   {
    "row": 1,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 418,
    "raftLeft": 863,
    "raftRight": 1227,
    "raftBottom": 785,
    "bodyArea": 10951,
    "box": [
     888,
     531,
     1229,
     791
    ]
   },
   {
    "row": 2,
    "col": 0,
    "cell": 418,
    "cellX": 0,
    "cellY": 836,
    "raftLeft": 25,
    "raftRight": 387,
    "raftBottom": 1176,
    "bodyArea": 10045,
    "box": [
     48,
     917,
     388,
     1183
    ]
   },
   {
    "row": 2,
    "col": 1,
    "cell": 418,
    "cellX": 418,
    "cellY": 836,
    "raftLeft": 445,
    "raftRight": 808,
    "raftBottom": 1177,
    "bodyArea": 10459,
    "box": [
     468,
     926,
     810,
     1184
    ]
   },
   {
    "row": 2,
    "col": 2,
    "cell": 418,
    "cellX": 836,
    "cellY": 836,
    "raftLeft": 860,
    "raftRight": 1226,
    "raftBottom": 1177,
    "bodyArea": 10311,
    "box": [
     884,
     917,
     1227,
     1184
    ]
   }
  ]
 }
};
PopoGame.FISH_ATLAS = {"width": 2048, "height": 550, "boxes": {"triangle": [0, 0, 252, 241], "square": [260, 0, 495, 258], "rectangle": [503, 0, 788, 228], "circle": [796, 0, 1056, 256], "rhombus": [1064, 0, 1298, 284], "parallelogram": [1306, 0, 1583, 228], "trapezium": [1591, 0, 1865, 234], "pentagon": [0, 292, 248, 550], "hexagon": [256, 292, 514, 546], "octagon": [522, 292, 761, 542], "nonagon": [769, 292, 1011, 539], "decagon": [1019, 292, 1264, 542], "oval": [1272, 292, 1566, 490], "semicircle": [1574, 292, 1749, 541], "triangle-right": [1757, 292, 2005, 515]}};
